### ISSUE TITLE
MacOS runNative Game Freeze on Startup (red screen)

### ISSUE THREAD

**Issue by Kotlin-Native** [korlibs/korge#1078]
Running 'runNative' on Mac OS 12.6 (Intel) and Korge 3.3 doesn't work. From logs I just get this:
```
> Task :runNativeMacosX64Release
Korui[0]
CanvasApplicationEx.IN[0]
2022-10-30 18:11:35.060 myTestGame.kexe[97701:5467609] Korgw.GameWindow.TooManyCallbacks, Too many callbacks to handle in this frame elapsedTime=22ms, availableTime=15ms pending timedTasks=1, tasks=0, processedTimedTasks=0, 
```
The App just shows a red screen and does not react anymore. Then i have to force quit it.
<img width="548" alt="Bildschirmfoto 2022-10-30 um 21 15 32" src="https://user-images.githubusercontent.com/839591/198899903-f629d482-35fd-4abd-8c81-b83db1dd6c34.png">

It doesn't matter if I load a TileMap or do nothing. This code snipped is already enough to reproduce it:
```
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors["#000000"]) { }
```

**Comment by soywiz** [comment]
@Kotlin-Native Which KorGE version are you using?

**Comment by Kotlin-Native** [comment]
Oh, forget to say the version 😅
3.3

**Comment by Kotlin-Native** [comment]
I've enabled debug and got some more logs. That's the last entries:
```
PrintAG: createBuffer():0
PrintAG: bufferCreate: 1
PrintAG: createBuffer():1
PrintAG: bufferCreate: 2
PrintAG: createBuffer():2
PrintAG: bufferCreate: 3
PrintAG: createBuffer():3
PrintAG: bufferCreate: 4
PrintAG: createBuffer():4
PrintAG: bufferCreate: 5
```

If I run JVM, the next log shows `Using DisplayLink` which is never logged in the native version

**Comment by soywiz** [comment]
Can you record a video showing the issue? Also, which mac model is?

For me it seems to work properly

**Comment by Kotlin-Native** [comment]
https://user-images.githubusercontent.com/839591/198901546-673a7630-325c-4309-9598-68c77267b23b.mov

<img width="279" alt="Bildschirmfoto 2022-10-30 um 22 06 59" src="https://user-images.githubusercontent.com/839591/198901624-1715dd2c-aafa-4f87-8a6b-95b09fe3416b.png">

**Comment by soywiz** [comment]
@Kotlin-Native To confirm: Do your mac have touchbar?

**Comment by soywiz** [comment]
@Kotlin-Native another question: can you try korge 3.1 and see if it works there? And downgrade versions until one of them works? To bisect the problem?

**Comment by Kotlin-Native** [comment]
@soywiz yep. It's still with touchbar.

It doesn't work in any 3.x version.
If I use 2.x in the beginning I also get a red screen but mostly for just a second and after that the game starts. But also in the latest version of 2 from time to time the game didn't start and hang in the red screen. In older versions of 2.x it looks like that it always load after the red screen.

I've tested it with the samples project. Not sure if it's really the latest v2 release, or it maybe was not up-to-date

**Comment by soywiz** [comment]
@Kotlin-Native Okay, I have investigated a bit further. I have tried to use XCode to simulate a touchbar, but I was unable to reproduce your problem with either Arm64 or X64. So I will need your help here:

Please, download this repo and try to execute it:

```sh
git clone https://github.com/korlibs/korge.git
cd korge
./gradlew :korge-sandbox:runJvm
./gradlew :korge-sandbox:runNativeDebug
```

Also please try:

```sh
MACOS_USE_DISPLAY_LINK=false ./gradlew :korge-sandbox:runNativeDebug
```

Now if you are reproducing the hang here, can you try to put a few println, to figure out up to where is it executing?
Let me explain the entrypoint:

This should be executed when the application runs:
https://github.com/korlibs/korge/blob/c4bc1ffeb0a8d2ab6ba025853af364c3b7aa5724/korgw/src/macosMain/kotlin/com/soywiz/korgw/DefaultGameWindowMacos.kt#L552

Then you can try to put a println in the main of korge code here:
https://github.com/korlibs/korge/blob/c4bc1ffeb0a8d2ab6ba025853af364c3b7aa5724/korge-sandbox/src/commonMain/kotlin/Main.kt#L31

And then if nothing shows the Korge block:
https://github.com/korlibs/korge/blob/c4bc1ffeb0a8d2ab6ba025853af364c3b7aa5724/korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt#L175

If you can figure out the code where it stops being executed, we could figure out a bit more the root cause of the issue

**Comment by Kotlin-Native** [comment]
After a first look:
Without displayLink it works fine.
createDisplayLink() returns as expected true

I think for some reason the render stopped to be triggered.
By set waiting of renderer to false everything works fine:
```
NSOperationQueue.mainQueue.addOperations(
        listOf(NSBlockOperation().also { it.addExecutionBlock(doDisplayCallbackRender) }),
        waitUntilFinished = false
    )
```

But now the strange part. By adding logging to the callback:
```
@SharedImmutable
val doDisplayCallbackRender: () -> Unit = {
    val gameWindow = atomicDisplayLinkContext.value?.asStableRef<MyDefaultGameWindow>()
    println(gameWindow)
    println(gameWindow?.get())
    gameWindow?.get()?.doRender(update = true)
}
```
it's also working fine. For me it looks like a strange timing issue 🤔

**Comment by soywiz** [comment]
Awesome @Kotlin-Native thanks for the investigation!

Maybe we can put a try catch there (in doDisplayCallbackRender) and figure out if something failed? Maybe we can log into an array without printing to ensure it is faster than a println, and dump that array in a separate timer to figure out if it is being called. We can also try to measure how much does it take for the `doDisplayCallbackRender` to execute and log (in addition to the try catch), to figure out if timing is important.

But since I cannot reproduce it, could you try that?
My concern with setting `waitUntilFinished = false` is if we could end queueing too much stuff for frames that took too long

**Comment by soywiz** [comment]
Not relevant anymore
