### ISSUE TITLE
JPEGInfo on iOS "Not implemented"

### ISSUE THREAD

**Issue by Burtan** [korlibs/korge#1119]
Hi,
when trying to encode a Bitmap to jpeg on iOS I get an kotlin.NotImplementedError.

`image.encode(JPEGInfo) // image: Bitmap` 

Are there any dependencies I have to add other than 
`                api("com.soywiz.korlibs.korim:korim:3.4.0")
`?

**Comment by Burtan** [comment]
Sorry I missread, that only PNG/JPEG **decoding** is supported on all platforms. So I guess iOS JPEG encoding is not supported.

**Comment by soywiz** [comment]
It is not possible right now. I have created a PR for that (using native encoders):
https://github.com/korlibs/korge/pull/1120

Also have in mind that JPEGInfo is just for reading metadata. If you want a common JPEG writer, you can copy this JPEGEncoder into your code. It is not included in KorIM directly because of its license:

https://github.com/korlibs/korge/blob/ced74677f8c7f7012de0045d507656de1b4d459d/%40old/korim-jpeg/src/commonMain/kotlin/com/soywiz/korim/format/jpg/JPEGEncoder.kt
