### ISSUE TITLE
Transformation to local coodinates is broken in Korge 3.4.0

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#1129]
It seems that the transformation of coordinates from global (screen/window based) to local (virtual size) is broken.

### What do I want to achive
Get the local coordinates from a MouseEvent (which provides global cocoordinates).
``` kotlin
override fun onMouseEvent(views: Views, event: MouseEvent) {
    val posLocal = Point()
    view.globalToLocalXY(event.x.toDouble(), event.y.toDouble(), posLocal)
    val globalPos = "x${posLocal.x}y${posLocal.y}"
}
```
### What do I expect
The globalPos field should hold the local coorindates.

### What do I get
The unchanged global coordinates.

### System
Tested on Korge 3.0.0 and 3.4.0. Problem on JVM and JS Build.

### Full Example
```kotlin
import com.soywiz.korev.*
import com.soywiz.korge.*
import com.soywiz.korge.component.*
import com.soywiz.korge.scene.*
import com.soywiz.korge.view.*
import com.soywiz.korim.color.*
import com.soywiz.korim.format.*
import com.soywiz.korio.file.std.*
import com.soywiz.korma.geom.*

suspend fun main() = Korge(width = 256, height = 256, virtualWidth = 256, virtualHeight = 256, bgcolor = Colors["#2b2b2b"]) {
    val sceneContainer = sceneContainer()
    sceneContainer.changeTo({ MyScene() })
}

class MyMouseListener(override val view: Container) : MouseComponent{
    val  infoPosGlobal = Text("")
    val  infoPosLocal = Text("")
    init {
        view.addChild(infoPosGlobal)
        view.addChild(infoPosLocal)
        infoPosLocal.position(0,50)
        view.addComponent(this as MouseComponent)
    }
    override fun onMouseEvent(views: Views, event: MouseEvent) {
        infoPosGlobal.text = "x${event.x}y${event.y}"
        val posLocal = Point()
        view.globalToLocalXY(event.x.toDouble(), event.y.toDouble(), posLocal)
        infoPosLocal.text = "x${posLocal.x}y${posLocal.y}"
    }

}
class MyScene : Scene() {
    override suspend fun SContainer.sceneMain() {
        addComponent(MyMouseListener(this))
        image(resourcesVfs["korge.png"].readBitmap()) {
            anchor(.5, .5)
            scale(0.1)
            position(128, 128)
        }

    }
}

```
### Screenshots
The screenshots shows, that the transformed coordinates are always the global ones.
In the middle should be 128 x 128. But dependent on Window size and Windows scaling (150%) this value does not match.

![JVM-150%](https://user-images.githubusercontent.com/1190109/203802536-628917d2-16e9-49eb-a6e5-d0bc8587d4a4.png)
![Web](https://user-images.githubusercontent.com/1190109/203802538-5b75ccb3-dc07-4560-b43c-a10dd3c6eee0.png)
<img width="584" alt="Web-150%" src="https://user-images.githubusercontent.com/1190109/203802525-812f5ba2-fb81-423b-9433-b399f130b913.png">
<img width="193" alt="JVM" src="https://user-images.githubusercontent.com/1190109/203802533-fee732da-e99d-4761-8a44-6493aa185581.png">

**Comment by soywiz** [comment]
@TobseF I believe this is the expected behaviour. But let me elaborate so you can contrast if it is the case:

In KorGE 2.0 scaling the window or using retina displays, meant that the Stage singleton view was updated to change the scale and position, that affected the global position. Also changed descendant view global positions. That was problematic in several ways, and was not how AS3 used to work.

In KorGE 3.0 now the Stage instance has always the identity transform matrix. That means that global positions are not window coordinates anymore, but coordinates relative to the global virtual coordinates. It is possible now to get window coordinates with another properties/methods, but usually discouraged since doing that arithmetic properly is usually error-prone. Most of the time working with our virtual dimensions/coordinate-system simplifies everything and is enough.
And again, I believe this is how AS3 used to work.

Please, let me know if after reading this it makes sense or you believe there is still something wrong, so I can check it further when I get back from my holiday break.

**Comment by TobseF** [comment]
Ok, good to know. In my case, I fixed it with:
```koltin
override fun onMouseEvent(views: Views, event: MouseEvent) {
    val mousePos = Point()
    view.localMouseXY(views, mousePos)
}
```
I use the `mousePos` coordinate to mathematically calculate the clicked field on a grid (like a chess board) in my _CandyCrush_ game.
To ignore the values provided in the `MouseEvent` and use `localMouseXY` instead, seems to be hard to figure out for beginners. To make it easier I would enhance the `MouseComponent` api and add the transformation function or properties for the local coordinates.
