### ISSUE TITLE
Procedurally generated tilemap (load tilemap from XML instead of file)

### ISSUE THREAD

**Issue by heathwinning** [korlibs/korge#150]
I'd like to be able to randomly/procedurally generate a tilemap, and my plan was to generate the `.tmx` file with the Korio XmlBuilder and load that instead of a file. I copied the source for `VfsFile.readTiledMap(...)` to hack a `Xml.readTiledMap(folder: VfsFile, ...)` but found that a few other classes were private so I decided to create this issue instead. Does it make sense for this to be added to korge?

I'm open to other suggestions to achieve the procedurally generated tilemap.

**Comment by soywiz** [comment]
A few suggestions/ideas:

* Here is a tilemap writer: https://github.com/korlibs/korge-intellij-plugin/blob/fd1efcf82aac4cf258ca80f01c1b773225ed6147/src/main/kotlin/com/soywiz/korge/intellij/editor/tile/TiledMapWriter.kt it is duplicated there since we wanted to evolve it first before backporting here without having to make korge releases
* KorIO allows you to create a VFS from memory (and thus getting a VfsFile instance).  https://github.com/korlibs/korio/blob/0aab43e05681f47e1c799246c8efef7dd071389f/korio/src/commonTest/kotlin/com/soywiz/korio/vfs/MemoryVfsTest.kt#L8 -- Though this overload is nicer to construct them while being immutable: https://github.com/korlibs/korio/blob/0aab43e05681f47e1c799246c8efef7dd071389f/korio/src/commonMain/kotlin/com/soywiz/korio/file/std/MemoryVfs.kt#L20 -- You can construct it in-memory then read from there
* Maybe you don't even need the intermediate XML. Why you don't load a template with the right size, and then mutate the TileMap with your own data? OR do you want to write it into a local file?

**Comment by heathwinning** [comment]
> OR do you want to write it into a local file?

Yes, once the tilemap is generated I want to save it locally, and the XML seemed like a good candidate for saving.

But, now that you've shown me the tilemap writer, I can construct the tilemap directly and generate XML to save. Thanks!
