### ISSUE TITLE
Unable to add Jitto icon in IntelliJ IDEA version 2023.1.1

### ISSUE THREAD

**Issue by ijero** [korlibs/korge#1594]
I added the Jitto icon in Customize Toolbar, but it's not showing up. I want to try using it with AI functionality like in the YouTube video. Is there a way to do this?

![8336418363fd718c20390ea24b46e06](https://github.com/korlibs/korge/assets/7928858/6f180fb8-166d-443e-beaf-624c5a705b4b)

**Comment by soywiz** [comment]
Currently published version is a bit outdated, and since the experience is not ready to use it is only enabled for me.

But if you are interested into trying it out you can like this:

Clone this repo: https://github.com/korlibs/korge-intellij-plugin
And open the project

Comment-out this line: https://github.com/korlibs/korge-intellij-plugin/blob/0c8a775fac4ed2fc3dd0a218b52f9b1b3bbfa81b/src/main/kotlin/com/soywiz/korge/intellij/actions/KorgeJittoAssistantAction.kt#L38

Run:
```bash
./gradlew runIde
```

You will need your own `OPENAI_KEY` from here: https://platform.openai.com/account/api-keys
When running the action for the first time, it will ask for it.

**Comment by ijero** [comment]
Thank you, following your steps, I rebuilt the plugin and it started working.
