### ISSUE TITLE
Reading from resourceVfs in a new CoroutineScope crashes on Android 

### ISSUE THREAD

**Issue by jobe-m** [korlibs/korge#1799]
My use-case is to be able to read files from resourceVfs from a "non-suspending" function like an updater. For that a new CoroutineScope needs to be set up where the suspending readBitmap() function is called. (At least this is how I understand it.)

Here is a short example which reproduces the issue: https://github.com/jobe-m/KorioExample

On JVM my example works. But when running on Android it crashes with:

```
[...]
07-17 00:32:26.728  2859  2980 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
07-17 00:32:26.728  2859  2980 E AndroidRuntime: Process: com.sample.demo, PID: 2859
07-17 00:32:26.728  2859  2980 E AndroidRuntime: java.lang.IllegalStateException: Android context not set! Please call `withAndroidContext()` method in your coroutine body. Current context: [StandaloneCoroutine{Active}@1358ca3, Dispatchers.IO]
07-17 00:32:26.728  2859  2980 E AndroidRuntime: 	at korlibs.io.android.KorioAndroidContextKt.androidContext(KorioAndroidContext.kt:29)
07-17 00:32:26.728  2859  2980 E AndroidRuntime: 	at korlibs.io.android.KorioAndroidContextKt.androidContext(KorioAndroidContext.kt:31)
07-17 00:32:26.728  2859  2980 E AndroidRuntime: 	at korlibs.io.file.std.AndroidResourcesVfs.readRange(VfsAndroid.kt:109)
07-17 00:32:26.728  2859  2980 E AndroidRuntime: 	at korlibs.io.file.VfsFile.readAll(VfsFile.kt:84)
07-17 00:32:26.728  2859  2980 E AndroidRuntime: 	at korlibs.io.file.VfsFile.read(VfsFile.kt:86)
07-17 00:32:26.728  2859  2980 E AndroidRuntime: 	at korlibs.io.file.VfsFile.readAsSyncStream(VfsFile.kt:102)
[...]
```

Maybe I do something wrong in the example code. I would appreciate to get my use-case working :)

**Comment by soywiz** [comment]
Just change:

```
CoroutineScope(Dispatchers.CIO).launch {
```

to:

```
launchImmediately {
```

Rationale:

The `SceneContainer` is a `CoroutineScope`.

https://github.com/korlibs/korge/blob/0289a0392377bdd2d42fae2e3ac8570b3c34914e/korge/src/commonMain/kotlin/korlibs/korge/scene/SceneContainer.kt#L62

You cannot use global dispatchers `Dispatchers.something`. You need to use the CoroutineContext from KorGE that dispatches to the right thread and includes all the contexts required.

LT;DR;

That's because `resourcesVfs` in Android uses the Context from Android. It is not a good practice to store that statically globally (that for example disallows fast refresh), so it is in the coroutine context.

If at some point you need blocking I/O, then yes, you can like resolve the final file and use Dispatchers.CIO. But `readBitmap` already offloads I/O and image decoding to a separate thread.

**Comment by jobe-m** [comment]
Thanks, I will try it out :)

**Comment by jobe-m** [comment]
Looks good now. When I use
```
    launchImmediately(context = coroutineContext) { ... }
```
it works on Android. The `coroutineContext` is saved in my game controller class when it is created in the SceneContainer with the coroutineContext of it. I can then call the launchImmediately from non-suspending functions. :)
