### ISSUE TITLE
Are mp3 & ogg sounds supported?

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#18]
I tried loading sound files in this way:

``` kotlin
    val formats = AudioFormats().registerStandard()
    val sound = resourcesVfs["sounds/circle_ok.ogg"].readAudioData(formats)
```

but it crashes with:
```
Exception in thread "kotlinx.coroutines.DefaultExecutor" com.soywiz.korio.lang.InvalidOperationException: Can't decode audio file JailVfs(ResourcesVfs[])[/sounds/circle_ok.mp3]
	at com.soywiz.korio.lang.ExceptionsKt.invalidOp(Exceptions.kt:29)
	at com.soywiz.korau.sound.AudioDataKt.readAudioData(AudioData.kt:93)
	at MainKt$main$2.invokeSuspend(main.kt:30)
```

Are **mp3** and **ogg** files supported in jvm desktop run? Or is there a special encoding which should be used for sound files?

It seems to be supported:
``` kotlin
AudioFormats.registerStandard(): AudioFormats = this.apply { register(WAV, OGG, MP3) } 
``` 
I tired it with this sound, but only the **wav** version works:
http://temp.tobsefritz.de/circle_ok.mp3
http://temp.tobsefritz.de/circle_ok.ogg
http://temp.tobsefritz.de/circle_ok.wav

**Comment by soywiz** [comment]
You have to include additional artifacts to support mp3 and ogg on the JVM:
https://github.com/korlibs/korge-samples/blob/e1dc052347da2404269326956e797b3c5b571f11/sample-lipsync/build.gradle#L5

Typically for now the most supported format to use natively is MP3 and now all the patents should have been expired.
* https://caniuse.com/#feat=mp3
* https://caniuse.com/#search=vorbis
* https://caniuse.com/#search=opus

I have separated mp3 decoding from the main korau since the library I was using has a separate license. I plan to switch to a public domain implementation in a future version.

while WAV object provides info + decoding + encoding:
* https://github.com/korlibs/korau/blob/c1dc966aedfe854aec9903c0ed0684b122989d04/korau/src/commonMain/kotlin/com/soywiz/korau/format/WAV.kt

the MP3 and OGG objects:
* https://github.com/korlibs/korau/blob/c1dc966aedfe854aec9903c0ed0684b122989d04/korau/src/commonMain/kotlin/com/soywiz/korau/format/MP3.kt
* https://github.com/korlibs/korau/blob/c1dc966aedfe854aec9903c0ed0684b122989d04/korau/src/commonMain/kotlin/com/soywiz/korau/format/OGG.kt
just decode the format info.

MP3Decoder and OGGDecoder
* https://github.com/korlibs/korau/blob/c1dc966aedfe854aec9903c0ed0684b122989d04/korau-mp3/src/commonMain/kotlin/com/soywiz/korau/format/mp3/Mp3Decoder.kt
* https://github.com/korlibs/korau/blob/c1dc966aedfe854aec9903c0ed0684b122989d04/korau-ogg-vorbis/src/commonMain/kotlin/com/soywiz/korau/format/ogg/OGGDecoder.kt

I guess I should deprecate those `MP3` and `OGG` objects and call them something like `MP3Info` and `OGGInfo` to avoid confusions.

Korau, is designed to allow audio processing in a more generic way.
But for games, the recommended way is to use `NativeSound`. It will use a native decoder (except in the JVM that you have to include the artifact I have mentioned, and it will be used automatically without registering internally using a ServiceLoader https://github.com/korlibs/korau/blob/c1dc966aedfe854aec9903c0ed0684b122989d04/korau-mp3/src/jvmMain/resources/META-INF/services/com.soywiz.korau.format.AudioFormat )

**Comment by soywiz** [comment]
I have updated the documentation: https://github.com/korlibs/korlibs.soywiz.com/commit/849e9e1378cb28833dd1e6076ef927e39361c30d

**Comment by TobseF** [comment]
Thank you very much for the fast reply and the documentation update👍
Now MP3 in jvm and js works like a charm!
