### ISSUE TITLE
Is there a suspend free way of playing a sound?

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#19]
I noticed that i need to load all assets inside a **suspend** function (eg. `suspend fun VfsFile.readAudioData`). But is this also necessary for playing a sound (`.toNativeSound().play()`)? If I want to play a sound deep in my game logic, I have to make all functions on this way to a suspend function. But this seems to be even impossible if I want to trigger a sound during a `KeyEvent`, because the `fun onKeyEvent(views: Views, event: KeyEvent)` has no suspend.

So did I missed something in coroutines, korge or the KorAU API or is this the recommend way to only write suspend methods?

Btw.: The https://forum.soywiz.com seems to be down, which would be a better place for my question.
If I get it out, I could also help to improper the documentation.

**Comment by soywiz** [comment]
I have fixed forum.soywiz.com already. It was not configured to start on reboot, and that's why it was down.

Typically you won't use `readAudioData` (unless you want to read or manipulate the data) but `readNativeSound` that returns a native sound ready to play. It seems that the documentation misses that part.

You would then execute the non-suspend `play` method that returns a `NativeSoundChannel`:
https://github.com/korlibs/korau/blob/c1dc966aedfe854aec9903c0ed0684b122989d04/korau/src/commonMain/kotlin/com/soywiz/korau/sound/NativeSound.kt#L81-L117

**Comment by soywiz** [comment]
I have updated the documentation: https://github.com/korlibs/korlibs.soywiz.com/commit/849e9e1378cb28833dd1e6076ef927e39361c30d

**Comment by TobseF** [comment]
Good hint! The doku helps a lot, so thank you for updating it👍
