### ISSUE TITLE
Support XML and JSON spritesheets

### ISSUE THREAD

**Issue by emign** [korlibs/korge#190]
SpriteAnimations should be able to be generated with generic sprite sheet formats

examples:

[XML](https://github.com/korlibs/korge/files/4739475/Archiv.zip)
[css.zip](https://github.com/korlibs/korge/files/4739477/css.zip)
[json array.zip](https://github.com/korlibs/korge/files/4739478/json.array.zip)
[json Hash.zip](https://github.com/korlibs/korge/files/4739479/json.Hash.zip)
[less.zip](https://github.com/korlibs/korge/files/4739480/less.zip)

**Comment by soywiz** [comment]
Can you provide a sample file of each?

**Comment by dector** [comment]
There are bunch of [different popular formats](https://www.codeandweb.com/free-sprite-sheet-packer).

**Comment by emign** [comment]
added some links

**Comment by soywiz** [comment]
We are already supporting atlases. Maybe what we can do is to be able to construct a SpriteAnimation out of it? Since they are named and might have several animations, maybe we can provide a prefix. For example: For "RunRight01.png" we can say: construct an animation for "RunRight" with 16.milliseconds per frame. Then it gets all the textures starting with RunRight, sort them, and constructs the animation.
That would work for you?

**Comment by emign** [comment]
so you only want to support the atlas files?

**Comment by soywiz** [comment]
As far as I'm concerned the files you uploaded, are atlases (open those files in a text editor and compare with other atlases).
I wouldn't support the CSS/LESS ones though.

```
.readAtlas(...).getAnimation("RunRight")
```

**Comment by emign** [comment]
okay. It was a misunderstanding. I thought you were referencing the `.atlas` files which are generated by phaser editor. As it turned out: phaser `.atlas` files are just json hash spritesheets.

**Comment by soywiz** [comment]
So in the end I have supported XML and both JSON-based (array and hash) formats. From an atlas you can get a SpriteAnimation adding a prefix or a RegExp matching the elements you want to include there.

**Comment by soywiz** [comment]
Documentation here: https://korlibs.soywiz.com/korge/atlas/
