### ISSUE TITLE
Native compilation fails when using Kotlin experimental APIs

### ISSUE THREAD

**Issue by ArtunSubasi** [korlibs/korge#284]
OS: Ubuntu 18.04.5 LTS
Repo: https://github.com/ArtunSubasi/10-digits-puzzle

When running the gradle task `./gradlew compileKotlinLinuxX64` the compilation fails with the following error:

`> Task :compileKotlinLinuxX64 FAILED
e: /.../digits-puzzle/build/platforms/native-desktop/bootstrap.kt: (5, 98): This declaration is experimental and its usage must be marked with '@kotlin.time.ExperimentalTime' or '@OptIn(kotlin.time.ExperimentalTime::class)'`

I actually used the Kotlin experimental `Time` and `StdLibApi` in my project. The `main` method of my project is annotated with:
`@ExperimentalTime and @ExperimentalStdlibApi`

When compiling native, the `bootstrap.kt` file which is presumably generated by the Korge Gradle plugin contains a `main` method with does not have those annotations. Therefore, the compilation fails. I couldn't find a way to add those to the generated `bootstrap.kt`.

Is this a constraint of the experimental APIs or can the gradle task be extended to support experimental APIs?

**Comment by soywiz** [comment]
KorGE doesn't use kotlin.time yet because it is experimental. Klock provides a TimeSpan class similar to duration that is not marked as experimental.

If you plan to use in your main method experimental time, or other experimental APIs, since as you stated there is a bootstrap method that is executed before, you should use `@OptIn` instead of just `@ExperimentalTime`.
I believe that it is not reasonable to mark all the possible annotations in the bootstrap method, since you could use other libraries unknown to korge itself. What do you think? Does using `@OptIn(kotlin.time.ExperimentalTime::class)` work for you?

**Comment by ArtunSubasi** [comment]
Using the `@OptIn` annotations instead of the `@Experimental` annotations worked like a charm. Thanks!
