### ISSUE TITLE
IntelliJ Errors "...libraries compiled with an  older Kotlin/Native compiler and cant be read in IDE." with all Korge Projects

### ISSUE THREAD

**Issue by Lykdraft** [korlibs/korge#285]
I need a little help here,
when loading any Korge project I get an error message in IntelliJ: 
```
There are 72 third-party libraries attached to the project that were compiled with an 
older Kotlin/Native compiler and cant be read in IDE.

Please edit Gradle buildfile(s) to use Kotlin Gradle plugin version 1.4.0. Then re-import the project in IDE.
```

I have no idea how to do that. I went through all the gradle.* files, didn't find anything. 
Any help here?

Thanks,
tL.

**Comment by soywiz** [comment]
Thanks for stating the issue.

They probably dropped support for that because multiplatform is still experimental, but at least gradle should compile just fine.

We are actively working on KorGE 2.0 that will work with Kotlin 1.4, there is no plans  to release 1.x versions against Kotlin 1.4 due to the amount of work required for that.

We plan to release a 2.0 alpha soon.

You can see the status of korge 2.0 here: https://github.com/korlibs/korge-next and compile yourself with a single command "gradlew publishToMavenLocal"
