### ISSUE TITLE
Sound doesn't work correctly in Android:(

### ISSUE THREAD

**Issue by Suragul** [korlibs/korge#323]
My Android version is 5.1, Samsung Galaxy J1(2016) SM J-120F. When I run this code in PC https://github.com/Suragul/SoundExp all works fine, but when I run it in Android the game slows down (when player begins jump) and crashes when I move from Game scene to Lose scene three or more times. All works fine without sounds, that's why the reason of the crush is sounds.

**Comment by soywiz** [comment]
Reproduced. Checking

**Comment by soywiz** [comment]
I have fixed this already. The problem was that mp3 decoding happened on the fly instead of decoding when reading (that is the expected behaviour).
In your case I advise you to use WAV instead of MP3, since MP3 decoding right now is slow and it is intended for music files.
I will replace the MP3 decoding implementation with a faster one at some point. For now stick to WAV for sound effects.

**Comment by soywiz** [comment]
Also note that it is a good idea to preload sound and resources ingame when loading the game and reuse them for later instead of in the scene initialization, since that will happen several times

**Comment by Suragul** [comment]
Thank you very much!
