### ISSUE TITLE
Kotlin not configured

### ISSUE THREAD

**Issue by jgedri** [korlibs/korge#364]
Every time I start or load a KorGE project, the IDE gives me a message saying, "Kotlin not configured." I selected "Kotlin with Gradle" and now ever line in build.gradle.kts is underlined in red. There are a lot of "unresolved reference" errors.

**Comment by retroredge** [comment]
I see this error too on OSX.

Along with errors like:

Duplicate content roots detected: Path [/Users/name/dev/misc/korge-hello-world/build/platforms/native-ios] of module [korge-hello-world.iosArm64Main] was removed from modules [korge-hello-world.iosX64Main]

And this:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

Interestingly  ./gradlew runJvm will succesully launch the hello world example but I can't work on the Kotlin code or build files because of the errors

**Comment by soywiz** [comment]
(I'm checking old issues) Is this still an issue?

**Comment by davjhan** [comment]
I don't know about the OP but I still see from Intellij

```
Duplicate content roots detected: Path [/Users/name/dev/misc/korge-hello-world/build/platforms/native-ios] of module [korge-hello-world.iosArm64Main] was removed from modules [korge-hello-world.iosX64Main]

```

as reported by @retroredge

**Comment by soywiz** [comment]
The duplicated content root could make sense, but not sure it is related to the original issue.
Maybe that folder could be added to the common ios instead to avoid the duplicate contents root. Just created this issue for that: https://github.com/korlibs/korge-next/issues/416

Going to close this issue for now. Feel free to reopen if that's still an issue
