### ISSUE TITLE
XY relative to rectangle parent.

### ISSUE THREAD

**Issue by Kesanov** [korlibs/korge#378]
Wouldn't it make more sense for `xy` to set `xy` relative to parent? So that 
```
roundRect(400.0, 200.0, 0.0) {
  xy(200.0, 100.0)
  text("Hello") {
    xy(50.0, 25.0)
  }
}
```
Would show `Hello` at `xy = (250, 125)`?

**Comment by soywiz** [comment]
RoundRect shouldn't be a container. If it is the case, you are not adding the text to roundRect, but the container. They are probably siblings. You should probably create a container contsining the roundrect and the text.

Normally all the
If the radius of the corners is 0, you should probably use SolidRect instead that is much more performant.

you can debug those issues by pressing F7 in a JVM build. There you can see the views tree, the anchor points, dimensions and hierarchy of the tree

**Comment by Josef-Vonasek** [comment]
> Normally all the
The sentence is cut off.

I wonder then if `RoundRect` should even have methods like `text` when it isn't a container..

**Comment by soywiz** [comment]
Agree that the method being available is not nice.

That problem is related to DSL accessibility on nested places. We tried to narrow it, but due to limitations, that change introduced other problems. When Kotlin provides new methods to tackle this we will revisit it. For now it is a problem we should be aware of.

For your specific case I'd suggest something similar to:

```kotlin
container {
  xy(200, 100)
  solidRect(400, 200)
  text("Hello").xy(50, 25)
}
```

**Comment by soywiz** [comment]
This was fixed already at some point
