### ISSUE TITLE
Scaling issues with different build targets

### ISSUE THREAD

**Issue by emign** [korlibs/korge#47]
Building the exact same project for different targets results in different view scalings:

korge-plugin-version: 1.4.2 (JS targt from 1.4.1)

First image: MacosnativeX64
Second image: JVM (still AWT/Swing, not JNA)
Third: JS
<img width="1392" alt="Bildschirmfoto 2019-12-02 um 19 58 50" src="https://user-images.githubusercontent.com/5278352/69987723-6da76a80-1540-11ea-869d-08c4849de7b1.png">
<img width="1392" alt="Bildschirmfoto 2019-12-02 um 19 55 36" src="https://user-images.githubusercontent.com/5278352/69987724-6da76a80-1540-11ea-8cf6-27e21a08dc99.png">
<img width="952" alt="Bildschirmfoto 2019-12-02 um 20 10 32" src="https://user-images.githubusercontent.com/5278352/69987726-6e400100-1540-11ea-8c7f-a9cafda33e54.png">

**Comment by emign** [comment]
Add JVM windows to the list

**Comment by emign** [comment]
Only an update sincd 1.4.c now is live: It happens with the JNA target too
So the current state is:
JS/Browser: Fullscreen (but images get pixelated)
JNA/JVM/Native: Seems half width and half height

<img width="1472" alt="JS" src="https://user-images.githubusercontent.com/5278352/70600032-f41e1500-1bee-11ea-9010-e18c938c7b90.png">
<img width="1348" alt="JNA" src="https://user-images.githubusercontent.com/5278352/70600037-f6806f00-1bee-11ea-8369-c2431710b6fd.png">

**Comment by soywiz** [comment]
Note to myself: probably related to having the main display as retina and displaying the window in a secondary display without retina. So I will have to check the pixel device ratio when moved/resized

**Comment by soywiz** [comment]
I have hopefully fixed all the targets: `runJvm`, `runJvmFirstThread` and `runNative*` on mac. For the record, and as talked at slack. To validate this before the next version:

KorGE uses mavenLocal `~/.m2` folder first instead of jcenter/bintray. So if you clone korgw repo, and changes the `gradle.properties` `version=1.9.7.SNAPSHOT` to `version=1.9.6` and then install, you can try the changes with Korge `1.4.3c` that references that version locally.

To try it faster since native and other targets might take some more time to build. Let's do this first:

Clone the repo, change the gradle.properties, and then execute:
* `./gradlew publishJvmPublicationToMavenLocal`
* Then come to any sample and run: `./gradlew runJvm` and `./gradlew runJvmFirstThread`
I have tried with both retina and non-retina resolutions and even switched resolutions while running and seems to work fine. But please validate it you too and if you have an external monitor with different resolution would be great to know if it works there too (I guess it should).

Now to try the K/N version (that would take a few minutes since right now the compilation is pretty slow):
* Korgw: `./gradlew publishMacosX64PublicationToMavenLocal `
* Korge sample with 1.4.3c: `./gradlew runNativeDebug`

I have hopefully fixed the resolution, and the frame of the window that was not right (was having into account the titlebar too), also fixed the menu of the application not being clickable before deactivating/reactivating the app.

If it is fixed, this will be included in the next version, probably released later today.

**Comment by soywiz** [comment]
Should be fixed in 1.5.0d https://bintray.com/korlibs/korlibs/korge-plugins
