### ISSUE TITLE
The same image with same alpha renders differently at different positions

### ISSUE THREAD

**Issue by zhanghai** [korlibs/korge#840]
With the following code fragment:

```
suspend fun main() = Korge(width = 1024, height = 1024, bgcolor = Colors.WHITE) {
    val bitmap = resourcesVfs["korge.png"].readBitmap()
    fun Container.image(x: Int, y: Int) = image(bitmap, 0.0, 0.0) {
        position(x, y)
        alpha(0.5)
    }
    val image1 = image(0, 0)
    val image2 = image(512, 0)
    val image3 = image(0, 512)
    val image4 = image(512, 512)
}
```

The rendered result is:

![image](https://user-images.githubusercontent.com/4469895/179321624-9164ccf0-5ea5-4c0d-a29e-d48066015613.png)

One can notice that the images on the right seems a bit brighther than the images on the left. Taking a look at the pixels, the purple border on the left is `#9480b4`, but the purple border on the right is `#9d80c7`.

This might or might not be related to https://github.com/korlibs/korge/issues/827#issuecomment-1185383018.

**Comment by soywiz** [comment]
I have just checked this. I believe this might a perception issue: comparing the right border with the left border of the images might cause that, because there is a small gradient in the KorGE logo. I have put the screenshot image in a editing software and overlapped the logos and they seem to have the same values for the same positions.
In the same korge image the left border is around to `#9D80C7` while the right one is around `#9480B4`, and the bottom part is doing a gradient between those.

https://user-images.githubusercontent.com/570848/181908293-73352a83-905c-4d43-96e2-6b51d50a118a.mov
