### ISSUE TITLE
IdentityFilter makes Image in Container appear smaller/off by 1 pixel on right and bottom in 3.0.1

### ISSUE THREAD

**Issue by zhanghai** [korlibs/korge#969]
`IdentityFilter` makes `Image` in `Container` appear smaller/off by 1 pixel on right and bottom in 3.0.1. Notet that this seems a regression in 3.0.1 and I can't reproduce it in 3.0.0.

```kotlin
suspend fun main() = Korge(width = 1280, height = 720, bgcolor = Colors.CYAN) {
    container {
        filter = IdentityFilter
        image(resourcesVfs["magenta.png"].readBitmap())
    }
}
```

[magenta.png](https://user-images.githubusercontent.com/4469895/188507486-8cbd7cf7-47d1-4eb9-88f3-cfb5a0c000bd.png)

![screenshot](https://user-images.githubusercontent.com/4469895/188507533-9c43c152-74d8-4672-b8b6-c2b324ac47be.png)

**Comment by soywiz** [comment]
Woops. It seems the position adjustment didn't work properly.

I recently added (after `3.0.1`) a feature flag to do it differently to avoid those potential issues:

* https://github.com/korlibs/korge/commit/aa1bcd671dd86566ab4581c57b6884d57212d60c
* https://github.com/korlibs/korge/commit/4699cacd98c0d79cb0732b3c76935e5b3bf5e7bd

The problem was that some filters like the blur are sampling outside the texture and in webgl the only wrapping mode is to clamp to the edges and that caused artifacts on the edges when blurring, so I tried to allocate one or more rows/columns on the edges that were transparent. It was a bit hacky so I was trying another approach that was to actually do a sampling aware of the texture bounds to return a transparent color when being outside the texture, but that happens at the cost of doing more operations at the fragment shader, but might be better. Probably sampling/reading memory is much costlier than just doing a few checks on GPU registers.
